Create Desktop version
DianaBeki/Portfolio-website pull request #11
Opened 2022-11-11 12:49 UTC by DianaBeki

In this task I did the following;

- Created index.html file and added markup for the  desktop version.
- Created a style.css file to style the page according to the design.
- Configured linters

2022-11-11 13:03 UTC, ichala requested changes
Hi @DianaBeki 
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Great Design ✔️ 
- Clean Code ✔️ 
- No Linters Errors ✔️

 ## Required Changes ♻️

- [ ] 🛑 **_Check the comments below_** 

## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 13:03 UTC, ichala commented on index.html
> +        <h3 id="connect">LET’S CONNECT</h3>
- [ ] your website looks perfect and so clean, but as part of the requirements, you should maintain the design of the mobile version as well. kindly fix the headline section of the mobile version to match Figma design and your website will be perfect

![image](https://user-images.githubusercontent.com/89282221/201345852-391cc9e0-6a1e-457f-ae7b-1a963aae7213.png)

2022-11-11 17:37 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @DianaBeki👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_

## Optional:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 17:37 UTC, ha-manel commented on index.html
> +        <h1 id="title3">I’m Diana<br>Glad to see you!</h1>
- [ ] As requested by the previous reviewer kindly make the headline of the mobile version match the one in Figma. The header's `color` and `font-size` don't match the design 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/201397052-a2fb5746-ccad-4a72-a1c3-221ba60423e6.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/201397074-739362d4-e993-470c-acce-e8b982ee5074.png)

2022-11-11 17:37 UTC, ha-manel commented on index.html
> +    <img class="last-img"src="/images/Home Indicator/Light.png">
[Optional]

- [ ] Please consider fixing the `background-image` of the contact section in the mobile version. It's not showing, also it's better if you use CSS for background images instead of putting them in HTML 👍

2022-11-12 09:35 UTC, levy002 approved these changes
## Hello @DianaBeki 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/bKBM7H63PIykM/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 09:36 UTC, merged