Portfolio: add a contact form and finish the mobile version
DianaBeki/Portfolio-website pull request #7
Opened 2022-11-04 19:13 UTC by DianaBeki

The following was done in this task
- completed contact form section

2022-11-04 20:04 UTC, vickymarz requested changes
Hi @DianaBeki, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 20:04 UTC, vickymarz commented on index.html
>              <ul class="footer-list">
- [ ] KIndly increase the width of your textarea and input field to be on the same line as the contact section text description to match the Figma design 👍🏽 

Figma Design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/200064411-896ea8d4-a26b-4a9a-9e2b-7993e4c3765d.png)

Your Design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/200064650-afcab48d-6139-4650-b95f-b191ae73bb7c.png)

2022-11-05 19:23 UTC, ichala requested changes
Hi @DianaBeki 
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Good Design✔️ 
- No linters errors✔️

 ## Required Changes ♻️

- [ ] 🛑 **_Check the comments below_**

## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 19:23 UTC, ichala commented on style.css
> +  color: #b3bac5;
- [ ] as mentioned by the previous reviewer kindly increase the width of the textarea to match the other inputs

![image](https://user-images.githubusercontent.com/89282221/200137376-347618cf-fbdb-421e-9d25-00189dee6930.png)

2022-11-08 22:12 UTC, merged